language: node_js
node_js:
  - '4'
  - '5'
  - '6'
script:
  - npm run lint
  - npm run test
sudo: false
cache:
  directories:
    - node_modules
env:
  - secure: "pDtPJwpA9oQr/DhAteXImjrSww3Hv10ExFzj5IX8JZ9qv53E+8Xn8sevMzyktanrTqZ3+EzabUrKgKi4sIFONCz/jElaYbZ+RpLpT7r//eQk4Nf6fMuTBXSnmCfGo7+16e4h+NK/cYhpWxepjDmn6YogwyHsg2GinAlbohGP7sxXtJgexZkoHepZKjyhGSsNIOSSOviZt9VhIBjYU/d/tT1hRJdY4hXGqoiaKPhxeD7cb28KUx2eiOXCIbGTivNjw+Bivz+9HaLNYIPbwFjx5F9eennSjW43e28fyOVblNoPfOxEi2YmMiQM3YrNIdKr9NXrO4r3BIXDCrb2ozFiola+MtAaTAy1rOhyHTICrmXWCSf0kh004t4NpQvBxLon8+d+NcXxRVlrLVI5iiiRBAZVsu3ThAnjvN8RFcP9EMnsBJIsld10Xsbhlqz4O/mFZt+sIVC47NsZ+adtNgBok6yLJBD2O1a8omYtLQE1tuRFe1v16vz+w8lO8Yn2uJZqi1twliKVPS0ammsiyrolSThuc9sl1Ie0MFyLvYoqrLujQvgLQJdaWznvYpfevtIWl6Z13mWZNC8UJ9ix5s9Qu/Y5CBK5IURElrsrDmMffk04c49drGKp5WheQF2ERptthgu5Mf36qRetAG5pGwkWzZ7mhNNbWS/O0LYfwxqTEGI="

